#!/usr/bin/env python3
"""Local development lifecycle helper for Aegis v2."""

from __future__ import annotations

import argparse
import json
import os
import platform
import shutil
import socket
import subprocess
import sys
import time
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / "frontend"
STATE_DIR = ROOT / ".aegis"
STATE_FILE = STATE_DIR / "devserver.json"
BACKEND_ENV = ROOT / ".env"
FRONTEND_ENV = FRONTEND / ".env.local"
BACKEND_PORT = 8000
FRONTEND_PORT = 3000


BACKEND_DEFAULTS = {
    "AEGIS_ENVIRONMENT": "development",
    "AEGIS_API_PREFIX": "/api/v1",
    "AEGIS_DATABASE_URL": "postgresql+asyncpg://aegis:aegis@localhost:5432/aegis",
    "AEGIS_LLM_PROVIDER": "disabled",
    "AEGIS_OPENAI_API_KEY": "",
    "AEGIS_ANTHROPIC_API_KEY": "",
    "AEGIS_GEMINI_API_KEY": "",
    "AEGIS_HUGGINGFACE_API_KEY": "",
    "AEGIS_OLLAMA_BASE_URL": "http://localhost:11434",
}

FRONTEND_DEFAULTS = {
    "NEXT_PUBLIC_AEGIS_API_URL": "http://localhost:8000",
    "NEXT_PUBLIC_AEGIS_WS_URL": "ws://localhost:8000/api/v1/events",
}


def info(message: str) -> None:
    print(f"[aegis] {message}")


def warn(message: str) -> None:
    print(f"[aegis:warn] {message}")


def fail(message: str, code: int = 1) -> None:
    print(f"[aegis:error] {message}", file=sys.stderr)
    raise SystemExit(code)


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def run(command: list[str], cwd: Path = ROOT) -> None:
    info(f"running: {' '.join(command)}")
    completed = subprocess.run(command, cwd=cwd)
    if completed.returncode != 0:
        fail(f"command failed with exit code {completed.returncode}: {' '.join(command)}")


def command_exists(name: str) -> bool:
    return shutil.which(name) is not None


def command_path(name: str) -> str | None:
    return shutil.which(name)


def venv_dir() -> Path:
    return ROOT / ".venv"


def venv_python() -> Path:
    if platform.system() == "Windows":
        return venv_dir() / "Scripts" / "python.exe"
    return venv_dir() / "bin" / "python"


def parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def merge_env(base: dict[str, str], path: Path) -> dict[str, str]:
    merged = dict(base)
    merged.update(parse_env_file(path))
    return merged


def ensure_env_file(path: Path, defaults: dict[str, str], title: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    existing_text = path.read_text(encoding="utf-8") if path.exists() else ""
    existing = parse_env_file(path)
    missing = [(key, value) for key, value in defaults.items() if key not in existing]

    if not path.exists():
        lines = [
            f"# {title}",
            "# Generated by scripts/dev_lifecycle.py. Fill secrets locally; do not commit this file.",
            "",
        ]
        lines.extend(f"{key}={value}" for key, value in defaults.items())
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        info(f"created {display_path(path)}")
        return

    if missing:
        suffix = ["", "# Added by scripts/dev_lifecycle.py"]
        suffix.extend(f"{key}={value}" for key, value in missing)
        path.write_text(existing_text.rstrip() + "\n" + "\n".join(suffix) + "\n", encoding="utf-8")
        info(f"updated {display_path(path)} with missing defaults")
    else:
        info(f"{display_path(path)} already has required keys")


def ensure_python_env(skip_install: bool = False) -> None:
    if not venv_python().exists():
        info("creating Python virtual environment at .venv")
        run([sys.executable, "-m", "venv", str(venv_dir())])
    else:
        info("Python virtual environment already exists")

    if skip_install:
        return

    python = str(venv_python())
    run([python, "-m", "pip", "install", "--upgrade", "pip"])
    run([python, "-m", "pip", "install", "-r", str(ROOT / "backend" / "requirements.runtime.txt")])


def ensure_frontend_deps(skip_install: bool = False) -> None:
    if skip_install:
        return
    npm = command_path("npm")
    if not npm:
        fail("npm was not found in PATH. Install Node.js 24+ or use Docker Compose.")

    node_modules = FRONTEND / "node_modules"
    if node_modules.exists():
        info("frontend dependencies already exist")
        return

    if (FRONTEND / "package-lock.json").exists():
        run([npm, "ci"], cwd=FRONTEND)
    else:
        run([npm, "install"], cwd=FRONTEND)


def load_state() -> dict:
    if not STATE_FILE.exists():
        return {}
    try:
        return json.loads(STATE_FILE.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        warn("state file is invalid; ignoring it")
        return {}


def save_state(state: dict) -> None:
    STATE_DIR.mkdir(exist_ok=True)
    STATE_FILE.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def pid_running(pid: int | None) -> bool:
    if not pid:
        return False
    try:
        os.kill(pid, 0)
        return True
    except OSError:
        return False


def port_open(host: str, port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.settimeout(0.25)
        return sock.connect_ex((host, port)) == 0


def port_guard(port: int, label: str) -> None:
    if port_open("127.0.0.1", port):
        state = load_state()
        service = state.get(label, {})
        pid = service.get("pid")
        if pid_running(pid):
            fail(f"{label} already appears to be running from this lifecycle state (pid {pid})")
        fail(f"port {port} is already in use; stop the owning process or choose Docker Compose")


def process_creation_options() -> dict:
    if platform.system() == "Windows":
        return {"creationflags": subprocess.CREATE_NEW_PROCESS_GROUP}
    return {"start_new_session": True}


def start_process(label: str, command: list[str], cwd: Path, env: dict[str, str]) -> dict:
    STATE_DIR.mkdir(exist_ok=True)
    stdout_path = STATE_DIR / f"{label}.log"
    stderr_path = STATE_DIR / f"{label}.err.log"
    stdout = stdout_path.open("ab")
    stderr = stderr_path.open("ab")
    process = subprocess.Popen(
        command,
        cwd=cwd,
        env=env,
        stdout=stdout,
        stderr=stderr,
        **process_creation_options(),
    )
    stdout.close()
    stderr.close()
    info(f"started {label} pid={process.pid}")
    return {
        "pid": process.pid,
        "command": command,
        "cwd": str(cwd),
        "stdout": str(stdout_path),
        "stderr": str(stderr_path),
        "started_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
    }


def terminate_pid(pid: int, label: str) -> None:
    if not pid_running(pid):
        info(f"{label} is not running")
        return
    if platform.system() == "Windows":
        subprocess.run(["taskkill", "/PID", str(pid), "/T", "/F"], capture_output=True, text=True)
    else:
        os.killpg(pid, 15)
    info(f"stopped {label} pid={pid}")


def command_setup(args: argparse.Namespace) -> None:
    ensure_env_file(BACKEND_ENV, BACKEND_DEFAULTS, "Aegis backend environment")
    ensure_env_file(FRONTEND_ENV, FRONTEND_DEFAULTS, "Aegis frontend environment")
    ensure_python_env(skip_install=args.skip_install)
    ensure_frontend_deps(skip_install=args.skip_install)
    info("setup complete")


def command_start(args: argparse.Namespace) -> None:
    if not args.no_setup:
        command_setup(argparse.Namespace(skip_install=args.skip_install))

    npm = command_path("npm")
    if not npm:
        fail("npm was not found in PATH. Install Node.js 24+ or use Docker Compose.")
    if not venv_python().exists():
        fail("Python virtual environment is missing. Run setup first or omit --no-setup.")

    state = load_state()
    if pid_running(state.get("backend", {}).get("pid")) or pid_running(state.get("frontend", {}).get("pid")):
        fail("a lifecycle-managed server is already running; use status or stop first")

    port_guard(BACKEND_PORT, "backend")
    port_guard(FRONTEND_PORT, "frontend")

    backend_env = merge_env(os.environ, BACKEND_ENV)
    frontend_env = merge_env(os.environ, FRONTEND_ENV)
    frontend_env.setdefault("NEXT_TELEMETRY_DISABLED", "1")

    backend = None
    try:
        backend = start_process(
            "backend",
            [
                str(venv_python()),
                "-m",
                "uvicorn",
                "backend.api.app:app",
                "--reload",
                "--host",
                "0.0.0.0",
                "--port",
                str(BACKEND_PORT),
            ],
            ROOT,
            backend_env,
        )
        frontend = start_process(
            "frontend",
            [npm, "run", "dev", "--", "--port", str(FRONTEND_PORT)],
            FRONTEND,
            frontend_env,
        )
    except OSError as exc:
        if backend:
            terminate_pid(int(backend["pid"]), "backend")
        fail(f"failed to start dev servers: {exc}")

    save_state({"backend": backend, "frontend": frontend})
    info("frontend: http://localhost:3000")
    info("backend:  http://localhost:8000/api/v1")


def command_stop(_: argparse.Namespace) -> None:
    state = load_state()
    if not state:
        info("no lifecycle state found")
        return
    for label in ("frontend", "backend"):
        service = state.get(label, {})
        pid = service.get("pid")
        if pid:
            terminate_pid(int(pid), label)
    if STATE_FILE.exists():
        STATE_FILE.unlink()
        info("removed lifecycle state")


def command_status(_: argparse.Namespace) -> None:
    state = load_state()
    for label, port in (("backend", BACKEND_PORT), ("frontend", FRONTEND_PORT)):
        service = state.get(label, {})
        pid = service.get("pid")
        running = pid_running(pid)
        listening = port_open("127.0.0.1", port)
        print(f"{label}: pid={pid or '-'} running={running} port={port} listening={listening}")
    if STATE_FILE.exists():
        print(f"state: {STATE_FILE}")
    else:
        print("state: none")


def doctor_line(label: str, ok_value: bool, detail: str, bad_status: str = "missing") -> None:
    status = "ok" if ok_value else bad_status
    print(f"{label}: {status} - {detail}")


def command_doctor(_: argparse.Namespace) -> None:
    doctor_line("python", sys.version_info >= (3, 12), sys.version.split()[0])
    doctor_line("venv", venv_python().exists(), str(venv_python().relative_to(ROOT)))
    doctor_line("npm", command_exists("npm"), "available in PATH" if command_exists("npm") else "not found")
    doctor_line("frontend deps", (FRONTEND / "node_modules").exists(), "frontend/node_modules")
    doctor_line("backend env", BACKEND_ENV.exists(), ".env")
    doctor_line("frontend env", FRONTEND_ENV.exists(), "frontend/.env.local")
    doctor_line("backend port", not port_open("127.0.0.1", BACKEND_PORT), f"{BACKEND_PORT}", "busy")
    doctor_line("frontend port", not port_open("127.0.0.1", FRONTEND_PORT), f"{FRONTEND_PORT}", "busy")
    doctor_line("docker", command_exists("docker"), "optional Docker Compose runtime")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Aegis v2 local development lifecycle")
    subparsers = parser.add_subparsers(dest="command", required=True)

    setup = subparsers.add_parser("setup", help="Create env files and install local dependencies")
    setup.add_argument("--skip-install", action="store_true", help="Create env files only")
    setup.set_defaults(func=command_setup)

    start = subparsers.add_parser("start", help="Start backend and frontend dev servers")
    start.add_argument("--no-setup", action="store_true", help="Do not run setup checks first")
    start.add_argument("--skip-install", action="store_true", help="Skip dependency installation during setup")
    start.set_defaults(func=command_start)

    stop = subparsers.add_parser("stop", help="Stop lifecycle-managed dev servers")
    stop.set_defaults(func=command_stop)

    status = subparsers.add_parser("status", help="Show lifecycle-managed process status")
    status.set_defaults(func=command_status)

    doctor = subparsers.add_parser("doctor", help="Check local prerequisites and ports")
    doctor.set_defaults(func=command_doctor)

    return parser


def main(argv: Iterable[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    args.func(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
